window.MACHINE_MAP = {
  "CHPR": "Chest Press",
  "INCHPR": "Incline Press",
  "DECHPR": "Decline Press",
  "PECDK": "Pec Deck / Chest Fly",
  "CABFLY": "Cable Fly (Chest)",
  "SMTH": "Smith Machine",

  "SHPR": "Shoulder Press",
  "LATRL": "Lateral Raise",
  "RDLT": "Rear Delt Fly",
  "UPROW": "Upright Row",

  "LATPD": "Lat Pulldown",
  "SETRW": "Seated Row",
  "HIRW": "High Row",
  "ASSTPD": "Assisted Pull-Up / Dip",
  "STRPD": "Straight-Arm Pulldown",
  "BKEXT": "Back Extension",
  "BENCHBP": "Barbell Bench Press",
  "INCBP": "Incline Barbell Bench Press",
  "DECBP": "Decline Barbell Bench Press",
  "TRAPDL": "Trap Bar Deadlift Station",
  "OLYPLT": "Olympic Lifting Platform",
  "DEADPL": "Deadlift Platform",
  "SAFESQ": "Safety Bar Squat Station",
  "REHYP": "Reverse Hyper Machine",
  "NORDIC": "Nordic Hamstring Bench",
  "FARMER": "Farmer's Carry Handles",
  "LANDRW": "Landmine Row Station",
  "CHESTST": "Chest-Supported Dumbbell Bench",
  "ADJBEN": "Adjustable Bench Station",
  "BULGSQ": "Bulgarian Split Squat Station",
  "HIPPLT": "Hip Thrust Platform",
  "CALFPR": "Standing Calf Press Machine",
  "ROWPLT": "Plate-Loaded Row Machine",
  "CHESTPL": "Plate-Loaded Chest Press",
  "INCHPL": "Plate-Loaded Incline Press",
  "SHOULDR": "Plate-Loaded Shoulder Press",
  "GLHAM": "Glute-Ham Developer (GHD) Station",
  "HIPEXT": "Hip Extension Machine",
  "ADDUCT": "Seated Adductor Machine",
  "ABROLL": "Ab Roller Track",
  "PUSHSL": "Prowler / Push Sled Lane",

  "LEGPR": "Leg Press",
  "HKSQ": "Hack Squat",
  "SQMT": "Squat Machine",
  "LEGEX": "Leg Extension",
  "LEGCUR": "Leg Curl",
  "SLCUR": "Seated Leg Curl",
  "LLCUR": "Lying Leg Curl",
  "STCUR": "Standing Leg Curl",
  "HIPAB": "Hip Abductor",
  "HIPAD": "Hip Adductor",
  "GLUTKB": "Glute Kickback",
  "SCALF": "Seated Calf Raise",
  "STCALF": "Standing Calf Raise",

  "PRCUR": "Preacher Curl",
  "BICUR": "Biceps Curl Machine",
  "CABCRL": "Cable Curl Station",
  "TRIEX": "Triceps Extension Machine",
  "DIPMT": "Dip Machine",
  "CABPD": "Cable Pushdown Station",

  "ABCR": "Ab Crunch Machine",
  "RTTOR": "Rotary Torso",
  "CAPCH": "Captain's Chair",
  "DABEN": "Decline Ab Bench",
  "CABAB": "Cable Crunch Station",

  "FBEN": "Flat Bench",
  "IBEN": "Incline Bench",
  "DBEN": "Decline Bench",
  "SQRK": "Squat Rack",
  "PWRK": "Power Rack",
  "DBRCK": "Dumbbell Rack",

  "TRED": "Treadmill",
  "TREAD": "Treadmill",
  "ELIP": "Elliptical",
  "STAIR": "Stair Climber",
  "BIKE": "Stationary Bike",
  "ROW": "Rower",

  "CROSS": "Cable Crossover / Functional Trainer",
  "CABLE": "Cable Station (Single)",
  "LATISO": "Iso-Lateral Lat Pulldown",
  "LTRW": "Low Row Machine",
  "TBRW": "T-Bar Row ",
  "CHSRW": "Chest-Supported Row",
  "PLOVR": "Pullover Machine",
  "FACEP": "Face Pull Station",
  "PULUP": "Pull-Up Bar / Rig",
  "CHINB": "Chin-Up Bar",
  "INVRT": "Inverted Row Station",

  "BPBEN": "Barbell Bench Press",
  "IBPBN": "Incline Barbell Bench Press (Bench)",
  "DBBEN": "Dumbbell Bench Press (Bench)",
  "IDBBN": "Incline Dumbbell Bench Press (Bench)",
  "LANDM": "Landmine Station",
  "JMPPR": "Jammer Press",
  "DPPRS": "Dip Station",
  "CHDIP": "Chest Dip Machine",
  "OHPRS": "Overhead Press Station",
  "SHRUG": "Shrug Machine",

  "GLBRG": "Glute Bridge / Hip Thrust Bench",
  "HIPTH": "Hip Thrust Machine",
  "BLSQT": "Belt Squat Machine",
  "VLEG": "Vertical Leg Press",
  "PENDL": "Pendulum Squat",
  "SISSY": "Sissy Squat Bench",
  "GHR": "Glute-Ham Raise (GHD)",
  "SLED": "Sled Push Track",
  "LUNGE": "Lunge Station",
  "SQTST": "Squat Stand / Platform",

  "HAMMR": "Hammer Strength Curl (Iso)",
  "TRICEPPRESS": "Tricep Press",
  "TRIDP": "Triceps Dip/Press Machine",
  "SKULL": "Skull Crushers Bench Area",
  "CLOSEB": "Close-Grip Bench Area",
  "EZBAR": "EZ Bar Rack",
  "BBRCK": "Barbell Rack",
  "PLTRK": "Plate Storage Rack",
  "KBRCK": "Kettlebell Rack",
  "MEDBL": "Medicine Ball Rack",
  "BAND": "Bands / Accessories Station",
  "TRX": "TRX / Suspension Trainer",
  "BOXJM": "Plyo Box Area",

  "PLANK": "Plank Station / Mat Area",
  "HANGK": "Hanging Knee Raise Station",
  "ABWHL": "Ab Wheel Area",
  "PALLF": "Pallof Press Station",

  "SEATDIP": "Seated Dip",
  "DEADLUNGE": "Deadlift Lunge",
  "CALFRAISE": "Calf Raise",
  "CABLEROW": "Cable Row",
  "DUALPULL": "Dual Adjustable Pulley",
  "SLGCUR": "Single Leg Curl",
  "ANGLP": "Angled Leg Press",
  "PULLDN": "Pulldown",
  "CONVSHPR": "Converging Shoulder Press",
  "PRONECUR": "Prone Leg Curl",
  "GLUTEXT": "Glute Extension",
  "ABDOM": "Abdominal",
  "DIVLROW": "Diverging Low Row",
  "DIVLATPD": "Diverging Lat Pulldown",
  "CONVCHPR": "Converging Chest Press",
  "MULTIPP": "Multi Pull Press",
  "RDPEC": "Rear Delt / Pec Fly",
  "OHBP": "Overhead Barbell Press",

  // --- Plate-loaded (Name - Plate) ---
  "SEATDIPPLATE": "Seated Dip - Plate Loaded",
  "TBRWPLATE": "T-Bar Row - Plate",
  "HIPTHPLATE": "Hip Thrust - Plate",
  "DEADLUNGEPLATE": "Deadlift Lunge - Plate",
  "CALFRAISEPLATE": "Calf Raise - Plate",
  "LATPDPLATE": "Lat Pulldown - Plate",
  "CABLEROWPLATE": "Cable Row - Plate",
  "DUALPULLPLATE": "Dual Adjustable Pulley - Plate",
  "SHPRPLATE": "Shoulder Press - Plate",
  "SLGCURPLATE": "Single Leg Curl - Plate",
  "LEGCURPLATE": "Leg Curl - Plate",
  "HKSQPLATE": "Hack Squat - Plate",
  "ANGLPPLATE": "Angled Leg Press - Plate",
  "LTRWPLATE": "Low Row - Plate",
  "SQMTPLATE": "Squat Machine - Plate",
  "SETRWPLATE": "Seated Row - Plate",
  "PULLDNPLATE": "Pulldown - Plate",
  "BCPL": "Biceps Curl- Plate Loaded",
  

  // --- Pin-loaded (Name - Pin) ---
  "SEATDIPPIN": "Seated Dip - Pin Loaded",
  "BCPN": "Biceps Curl- Pin Loaded",
  "LEGPRPIN": "Leg Press - Pin",
  "LEGEXPIN": "Leg Extension - Pin",
  "SLCURPIN": "Seated Leg Curl - Pin",
  "HIPABPIN": "Abductor - Pin",
  "LATRLPIN": "Lateral Raise - Pin",
  "CONVSHPRPIN": "Converging Shoulder Press - Pin",
  "ASSTPDPIN": "Dip / Chin Assist - Pin",
  "PRONECURPIN": "Prone Leg Curl - Pin",
  "GLUTEXTPIN": "Glute Extension - Pin",
  "TRIEXPIN": "Triceps Extension - Pin",
  "ABDOMPIN": "Abdominal - Pin",
  "RTTORPIN": "Rotary Torso - Pin",
  "BICURPIN": "Biceps Curl - Pin Loaded",
  "DIVLROWPIN": "Diverging Low Row - Pin",
  "DIVLATPDPIN": "Diverging Lat Pulldown - Pin",
  "CONVCHPRPIN": "Converging Chest Press - Pin",
  "MULTIPPPIN": "Multi Pull Press - Pin",
  "RDPECPIN": "Rear Delt / Pec Fly - Pin",

  // --- Added cardio machines ---
  "RECBK": "Recumbent Bike",
  "UPRBK": "Upright Bike",
  "ICLMB": "Incline Trainer",
  "JACOB": "Jacob's Ladder",
  "VCLMB": "Vertical Climber (VersaClimber)",
  "XTRNR": "Cross Trainer",
  "SPRBK": "Sprint Bike",
  "STRDR": "Strider",
  "ADSKI": "Air Ski Trainer",
  "SLDM": "Slide Mill / Lateral Trainer",
  "ASSLT": "Air Bike (Assault-Style)",
  "SKIER": "SkiErg",
  "CURVE": "Curved Manual Treadmill",
  "STEP": "Step Mill / Stepper",
  "SPIN": "Spin Bike",
  "ARC": "Arc Trainer"
};
